### ISSUE TITLE
上传了一张图片之后，chrome 的 console 突然跳出来这些：

### ISSUE THREAD

**Issue by zhuangya** [zhuangya/nova#33]
``` javascript

/data/nova/node_modules/imagemagick/imagemagick.js:156
        geometry = result['geometry'].split(/x/);
                                      ^
TypeError: Cannot call method 'split' of undefined
  at [object Object].callback (/data/nova/node_modules/imagemagick/imagemagick.js:156:39)
  at [object Object].Accumulator.finish (/data/nova/node_modules/imagemagick/imagemagick.js:60:55)
  at ChildProcess.<anonymous> (/data/nova/node_modules/imagemagick/imagemagick.js:86:11)
  at ChildProcess.EventEmitter.emit (events.js:99:17)
  at maybeClose (child_process.js:638:16)
  at Process._handle.onexit (child_process.js:680:5)

```

**Comment by bearice** [comment]
你传了一张不是图片的东西上去吧?

**Comment by zhuangya** [comment]
有可能。。
