### ISSUE TITLE
线上 「加入购物车」之后报了 500

### ISSUE THREAD

**Issue by zhuangya** [zhuangya/nova#47]
post 的 payload 是这样：

``` json

{"name":"tee/Castel_Sant_Angelo_Rome_T_shirt/default/s","count":1,"unit_price":399}

```

**Comment by zhuangya** [comment]
response:

```
TypeError: Cannot read property 'sizes' of undefined at Product.getPrice (/data/nova/src/product.coffee:52:11) at Cart.update (/data/nova/src/cart.coffee:19:6) at callbacks (/data/nova/node_modules/express/lib/router/index.js:164:37) at fibrous.middleware (/data/nova/node_modules/fibrous/lib/fibrous.js:167:18)
```

**Comment by zhuangya** [comment]
之前是我写的数据的事情， close it
